### ISSUE TITLE
The Vale Server topic displays obsolete pricing and omits mentioning the free open-source version.

### ISSUE THREAD

**Issue by rolfedh** [errata-ai/vale-atom#10]
The https://errata.ai/vale-server/ topic shows obsolete pricing and omits mentioning the free open source version.

![Screenshot from 2022-04-10 14-39-50](https://user-images.githubusercontent.com/350907/162634901-b2792aae-27d5-4829-9d6b-eba5f89d933d.png)

**Comment by jdkato** [comment]
See #9.
