### ISSUE TITLE
Does this project make "atomic-vale" obsolete?

### ISSUE THREAD

**Issue by TimKam** [errata-ai/vale-atom#2]
I am wondering if there still is a use case "atomic-vale", given this package. Also, _if_ atomic-vale is still relevant, I'd be happy to move it over/handover ownership if you think this makes sense.

**Comment by jdkato** [comment]
I think there are definitely still users of `atomic-vale`. And, yes, I'm willing to take over ownership/maintenance if you'd like.

In any case, I appreciate the work you've put into the package.

**Comment by TimKam** [comment]
Thanks for the prompt response. I added you as a collaborator to the project so that you can transfer it.

**Comment by jdkato** [comment]
Thanks -- I think I somehow missed the invitation, though. Could you send it again?

**Comment by TimKam** [comment]
You are already listed as a collaborator (not only _pending invitation_) can you check if you have the right permissions?
https://github.com/TimKam/atomic-vale

**Comment by jdkato** [comment]
Yes, I actually do have the permissions already. Sorry for the confusion.
