### ISSUE TITLE
Vocab not recognised

### ISSUE THREAD

**Issue by anthillsocial** [errata-ai/vale-atom#5]
Hi,

I installed the Vale Server package for atom. Though for some reason the atom package does not recognise spellings I added to a vocab via the dashboard.

I'm not sure what's going wrong here... So any help would be appreciated! 
Ta Tom

BTW I'm using Arch Linux.

**Comment by anthillsocial** [comment]
Just discovered that if I click on an empty line and save the file, this is what triggers the "unhandled promise rejection" errors. Other issues still stand though...

**Comment by jdkato** [comment]
There's a few things to check here:

1. Make sure you've enabled the correct Vocab in your project's config:

    ```ini
    StylesPath = "<omitted>"

    MinAlertLevel = suggestion

    # 'Test' should be the name of your desired Vocab.
    Vocab = Test

    [*]
    # List of styles to load.
    #
    # The 'Vale' style needs to be active.
    BasedOnStyles = Vale
    ```

2. Check that you're running in [`Server` mode](https://docs.errata.ai/vale-server/usage#choosing-a-mode).

3. Make sure that the project you've edited in step (1) is active (*Select Project* from the context menu).

**Comment by anthillsocial** [comment]
Brilliant. Putting Vocab before BasedOnStyles variable fixed it!
Thank you. BTW the docs dont refer to the "Vocab" variable in the project .init which added to my confusion. 

```
StylesPath = ""
MinAlertLevel = suggestio
Vocab = Test
[*]
BasedOnStyles = Vale, proselint
```

**Comment by jdkato** [comment]
There's a section on it in the [CLI docs](https://docs.errata.ai/vale/vocab), but it does need to be added to Server docs.
