### ISSUE TITLE
False positive for capitalisation 

### ISSUE THREAD

**Issue by anthillsocial** [errata-ai/vale-atom#6]
I've added the term "technicity" to a vocab for a project though its capitalisation after a full stop is incorrectly highlighted as an error. For example: 

"Here, my use of technicity does not generate an error. Technicity, after a full stop, does generate an error in this instance."

How do I prevent this from being highlighted as an error?

**Comment by jdkato** [comment]
You can add `[Tt]echnicity` to allow both cases.

**Comment by anthillsocial** [comment]
Thankyou! :)
