### ISSUE TITLE
Clicking "Get Vale Server for Linux" button produces 404 error 

### ISSUE THREAD

**Issue by rolfedh** [errata-ai/vale-atom#9]
1. Visit https://errata.ai/vale-server/
2. Click the "Get Vale Server for Linux button. This action opens https://github.com/errata-ai/errata.ai/releases/download/v1.0.0/Vale-Server-1.13.0-linux.AppImage, which produces a 404 error.

![Screenshot from 2022-04-10 14-39-50](https://user-images.githubusercontent.com/350907/162634807-33561e5d-7a42-4efd-a321-a9030b4b0bc1.png)
![Screenshot from 2022-04-10 14-42-09](https://user-images.githubusercontent.com/350907/162634810-670e7d82-f982-479b-945f-6cf2ee541420.png)

**Comment by jdkato** [comment]
I've updated the link to point to the new repo.
